// Generated by https://quicktype.io

import { Origin } from "./enum";

export interface APIRes {
    status:  string;
    message: string;
    data:    Data;
}

export interface Data {
    users?: User[];
    petTypes?: PetType[]
}

export interface User {
    id:        string;
    name:      string;
    lastname:  string;
    email:     string;
    role:      string;
    createdAt?: string;
    updatedAt?: string;
    password?: string
}

export interface PetType{
    id: string
    name: string
}

export interface Pet{
    id: string
    name: string
    desc: string
    raza: Breed
    owner: Owner
}

export interface Owner{
    id: string
    name: string
    email: string
    address: string
    contact1: string
    contact2: string
}

export interface Breed{
    id: string
    name: string
    type: PetType
    desc: string
}

export interface ModalProps{
    status: boolean
    message: string
    method: string
    color: Color
}

export interface ModalDeleteProps{
    status: boolean
    title: string
    selectedId: string
}

export interface TableProps{
    tableHeaders: string[]
    data: PetType[] | undefined
    fetching: boolean
    error: boolean
    editFn: (data: PetType) => void
    deleteFn: (id: string) => void
    origin: Origin
}

export interface ModalPetTypeEditProps{
    status: boolean
    selectedId: string
    selected: string
}
