// Generated by https://quicktype.io

import { Origin } from "./enum";

export interface APIRes {
    status:  string;
    message: string;
    data:    Data;
}

export interface Data {
    users?: User[];
    petTypes?: PetType[]
}

export interface User {
    id:        string;
    name:      string;
    lastname:  string;
    email:     string;
    role:      string;
    createdAt?: string;
    updatedAt?: string;
    password?: string
}

export interface PetType{
    id: string
    name: string
}

export interface Pet{
    id: string
    name: string
    desc: string
    raza: string
    owner: string
}

export type Owner = {
    id: string,
    name: string,
    email: string,
    address: string,
    contact1: string,
    contact2: string | undefined
}

export interface Breed{
    id: string
    name: string
    type: string
    desc: string
}

export interface ModalProps{
    status: boolean
    message: string
    method: string
    color: Color
}

export interface ModalDeleteProps{
    status: boolean
    title: string
    selectedId: string
}

export interface TableProps{
    tableHeaders: string[]
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    data: any[] | undefined
    fetching: boolean
    error: boolean
    editFn: (data) => void
    deleteFn: (id: string) => void
    origin: Origin
}

export interface ModalPetTypeEditProps{
    status: boolean
    selectedId: string
    selected: string
}

export interface ModalOwnersEditProps{
    status: boolean
    selected: Owner
}

export interface ModalOwnersDeleteProps{
    status: boolean,
    selected: string
}

export interface ModalBreedsEditProps{
    status: boolean
    selected: Breed
}

export interface ModalBreedsDeleteProps{
    status: boolean
    selected: string
}

export interface ModalPetsEditProps{
    status: boolean
    selected: Pet
}

export interface ModalPetsDeleteProps{
    status: boolean
    selected: string
}