// Generated by https://quicktype.io

export interface APIRes {
    status:  string;
    message: string;
    data:    Data;
}

export interface Data {
    users: User[];
}

export interface User {
    id:        string;
    name:      string;
    lastname:  string;
    email:     string;
    role:      string;
    createdAt?: string;
    updatedAt?: string;
    password?: string
}

export interface Pet{
    id: string
    name: string
    desc: string
    raza: string
    owner: string
}

interface ModalProps{
    status: boolean
    message: string
    method: string
    color: Color
}