// Generated by https://quicktype.io

export interface APIRes {
    status:  string;
    message: string;
    data:    Data;
}

export interface Data {
    users: User[];
}

export interface User {
    id:        string;
    name:      string;
    lastname:  string;
    email:     string;
    role:      string;
    createdAt: string;
    updatedAt: string;
}
