// Generated by https://quicktype.io

export interface APIRes {
    status:  string;
    message: string;
    data:    Data;
}

export interface Data {
    users?: User[];
    petTypes?: PetType[]
}

export interface User {
    id:        string;
    name:      string;
    lastname:  string;
    email:     string;
    role:      string;
    createdAt?: string;
    updatedAt?: string;
    password?: string
}

export interface PetType{
    id: string
    name: string
}

export interface Pet{
    id: string
    name: string
    desc: string
    raza: string
    owner: string
}

export interface ModalProps{
    status: boolean
    message: string
    method: string
    color: Color
}

export interface ModalDeleteProps{
    status: boolean
    title: string
    selectedId: string
}

export interface TableProps{
    tableHeaders: string[]
    data: PetType[] | undefined
    origin: string
    fetching: boolean
    error: boolean
}

export interface ModalEditProps{
    status: boolean
    selectedId: string
    selected: string
}
